name       : dconf
version    : 0.32.0
release    : 17
source     :
    - https://download.gnome.org/sources/dconf/0.32/dconf-0.32.0.tar.xz : 68bce78b19bc94cb2c3bb8587e37f9e5e338568c3a674f86edde9c9f1624ffab
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : GNOME Configuration Database
description: |
    The dconf package contains a configuration database system used by many GNOME applications.
emul32     : yes
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(gio-unix-2.0)
    - docbook-xml
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
