name       : dconf
version    : 0.26.0
release    : 14
source     :
    - http://ftp.gnome.org/pub/gnome/sources/dconf/0.26/dconf-0.26.0.tar.xz : 8683292eb31a3fae31e561f0a4220d8569b0f6d882e9958b68373f9043d658c9
homepage   : http://projects.gnome.org/dconf/
license    :
    - GPL-3.0
    - LGPL-2.0
builddeps  :
    - pkgconfig32(gio-unix-2.0)
    - dbus-32bit-devel
    - dbus-32bit
    - glibc-32bit-devel
    - libgcc-32bit
    - vala
emul32     : yes
summary    : GNOME Configuration Database
description: |
    The dconf package contains a configuration database system used by many GNOME applications.
setup      : |
    %configure --disable-static --disable-man --prefix=/usr --libexecdir=/usr/lib64/dconf
build      : |
    %make
install    : |
    %make_install
