name       : dconf
version    : 0.28.0
release    : 16
source     :
    - https://download.gnome.org/sources/dconf/0.28/dconf-0.28.0.tar.xz : 61d3b3865ef58b729c3b39aa0979f886c014aa8362f93dcfc74bf5648ed9c742
homepage   : https://wiki.gnome.org/Projects/dconf
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : GNOME Configuration Database
description: |
    The dconf package contains a configuration database system used by many GNOME applications.
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(gio-unix-2.0)
    - vala
emul32     : yes
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
