name       : dconf
version    : '0.38'
release    : 19
source     :
    - https://download.gnome.org/sources/dconf/0.38/dconf-0.38.0.tar.xz : 45f60f41330d27715cce1315af123f94f1c2cdedb68b6bed3b309866eec44f58
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : GNOME Configuration Database
description: |
    The dconf package contains a configuration database system used by many GNOME applications.
emul32     : yes
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(gio-unix-2.0)
    - docbook-xml
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
