name       : dconf
version    : 0.26.1
release    : 15
source     :
    - https://ftp.gnome.org/pub/gnome/sources/dconf/0.26/dconf-0.26.1.tar.xz : d583b1f7fc93b879e2956acc6a26ea05a445a0002158aeef80c8e378e1414535
homepage   : https://wiki.gnome.org/Projects/dconf
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : GNOME Configuration Database
description: |
    The dconf package contains a configuration database system used by many GNOME applications.
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(gio-unix-2.0)
    - vala
emul32     : yes
setup      : |
    %configure --disable-man --prefix=/usr --libexecdir=/usr/lib64/dconf
build      : |
    %make
install    : |
    %make_install
